// ui_kits/santai-web/data.jsx
// Shared product + content data for the Santai web UI kit
const SANTAI_PRODUCTS = [
  {
    id: "s02",
    code: "S02",
    name: "Style 02",
    variant: "Whisper · Natural",
    blurb: "Our gentlest curve. Where every first-timer starts.",
    price: "RM 79",
    drama: 1,
    eye: ["monolid", "hooded", "almond"],
    occasion: ["daily", "office"],
    tag: "First-timer pick",
    swatches: ["#1F1A17", "#3D332D"],
    bg: "#E8E0D3",
    lashWidth: 56,
    lashHeight: 2,
    image: "assets/photos/lash-petri-yellow.jpg",
  },
  {
    id: "s04",
    code: "S04",
    name: "Style 04",
    variant: "Doe Eye · Natural",
    blurb: "Soft, weightless, made for almond and hooded shapes.",
    price: "RM 89",
    drama: 2,
    eye: ["almond", "hooded", "round"],
    occasion: ["daily", "office", "date"],
    tag: "Bestseller",
    swatches: ["#1F1A17", "#3D332D", "#6B362C"],
    bg: "#D9CDB9",
    lashWidth: 64,
    lashHeight: 3,
    image: "assets/photos/lash-petri-orange.jpg",
  },
  {
    id: "s06",
    code: "S06",
    name: "Style 06",
    variant: "Editorial · Volumed",
    blurb: "A polished evening look, weightless on the lid.",
    price: "RM 95",
    drama: 3,
    eye: ["almond", "upturned"],
    occasion: ["date", "wedding"],
    tag: "New",
    swatches: ["#1F1A17"],
    bg: "#C9BDA9",
    lashWidth: 70,
    lashHeight: 4,
    image: "assets/photos/compact-silk-pearls.jpg",
  },
  {
    id: "s08",
    code: "S08",
    name: "Style 08",
    variant: "Festival · Drama",
    blurb: "When the brief says full drama. Photographs beautifully.",
    price: "RM 105",
    drama: 5,
    eye: ["round", "almond", "upturned"],
    occasion: ["wedding", "festival"],
    tag: "Award winner",
    swatches: ["#1F1A17", "#6B362C"],
    bg: "#3D332D",
    lashWidth: 76,
    lashHeight: 5,
    image: "assets/photos/compact-bag-yellow.jpg",
  },
  {
    id: "s03",
    code: "S03",
    name: "Style 03",
    variant: "Wispy · Natural",
    blurb: "Featherweight wisps, like your lashes only better.",
    price: "RM 85",
    drama: 2,
    eye: ["monolid", "downturned", "hooded"],
    occasion: ["daily"],
    tag: "",
    swatches: ["#1F1A17", "#3D332D"],
    bg: "#E8E0D3",
    lashWidth: 60,
    lashHeight: 3,
    image: "assets/photos/compact-yellow.jpg",
  },
  {
    id: "s07",
    code: "S07",
    name: "Style 07",
    variant: "Soft Glam · Volumed",
    blurb: "The dinner-out lash. Defined without the drama.",
    price: "RM 95",
    drama: 3,
    eye: ["almond", "round", "downturned"],
    occasion: ["date", "office"],
    tag: "",
    swatches: ["#1F1A17"],
    bg: "#D9CDB9",
    lashWidth: 68,
    lashHeight: 4,
    image: "assets/photos/compact-hand-green.jpg",
  },
];

const SANTAI_EYE_SHAPES = [
  { id: "almond", label: "Almond", icon: "../../assets/eye-shapes/almond.svg" },
  { id: "hooded", label: "Hooded", icon: "../../assets/eye-shapes/hooded.svg" },
  { id: "monolid", label: "Monolid", icon: "../../assets/eye-shapes/monolid.svg" },
  { id: "round", label: "Round", icon: "../../assets/eye-shapes/round.svg" },
  { id: "upturned", label: "Upturned", icon: "../../assets/eye-shapes/upturned.svg" },
  { id: "downturned", label: "Downturned", icon: "../../assets/eye-shapes/downturned.svg" },
];

const SANTAI_OCCASIONS = [
  { id: "daily", label: "Daily" },
  { id: "office", label: "Office" },
  { id: "date", label: "Date Night" },
  { id: "wedding", label: "Wedding" },
  { id: "festival", label: "Festival" },
];

const SANTAI_LOOKS = [
  { id: "natural", label: "Natural", desc: "Like yours, only better." },
  { id: "office", label: "Office Polished", desc: "Defined, never demanding." },
  { id: "soft", label: "Soft Glam", desc: "Dinner-out lashes." },
  { id: "drama", label: "Full Drama", desc: "When the brief says drama." },
];

Object.assign(window, {
  SANTAI_PRODUCTS,
  SANTAI_EYE_SHAPES,
  SANTAI_OCCASIONS,
  SANTAI_LOOKS,
});
